# ELK Stack for Log analysis
# This needs a ton of memory, sadly. The stuff is Java based and seems to waste
# memory and CPU cycles left, right and center.

version: '3.7'

volumes:
  esdata:

networks:
  logging:
  backend:

services:
  # Database / Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    command:
      - elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - logging
    deploy:
      replicas: 1

  # Parser
  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.0
    hostname: logstash
    depends_on:
      - elasticsearch
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    command: >-
      logstash --quiet -e '
        input { udp { port => 5000 codec => json } }
        filter { if [docker][hostname] =~ /^logstash/ { drop { } } }
        output { stdout { } elasticsearch { hosts => "elasticsearch:9200" } }
        '
    networks:
      - logging
    deploy:
      replicas: 1

  # Web Interface
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    hostname: kibana
    #image: bitnami/kibana
    networks:
      - logging
      - backend
    environment:
        - SERVER_REWRITEBASEPATH=false
        - SERVER_BASEPATH=/kibana
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 5601
        traefik.frontend.rule: Host:biocondabot.pruesse.net,localhost;PathPrefixStrip:/kibana
      replicas: 1

  # Sends logs from docker containers to logstash
  logspout:
    image: bekt/logspout-logstash
    hostname: logspout
    environment:
      ROUTE_URIS: logstash://logstash:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - logging
    depends_on:
      - logstash
