{% set name = "adpred" %}
<<<<<<< HEAD
{% set version = "1.2.4" %}
=======
{% set version = "1.1.3" %}
>>>>>>> 41826d2ea3058334d873fbd6798b35846fe6dd99

package:
  name: "{{ name }}" 
  version: "{{ version }}"

source:
  url: https://github.com/FredHutch/{{ name }}/archive/v{{ version }}.tar.gz  
<<<<<<< HEAD
  sha256: 983e10a2bbf5f70d17f8a96300d1801d60aaed76aebb7afb9d8072f12665971a
=======
  sha256: c4ba42e5f71c74036b168b0233b6004badc03d8b98244107393880280a3c1a75
>>>>>>> 41826d2ea3058334d873fbd6798b35846fe6dd99

build:
  number: 0
  noarch: python
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt 

requirements:
  host:
    - python >=3.6
    - setuptools==46
  run:
    - python >=3.6
    - keras==2.2.4
    - scikit-learn==0.21.3
    - numpy==1.17.2
    - plotly==4.1.1
    - tensorflow==1.14.0
    - requests==2.23.0
    - pandas

test:
  imports:
    - adpred

about:
  home: https://github.com/FredHutch/adpred
  license: MIT Licence
  summary: "python adpred module for prediction of Transcription activation domains from protein sequences"

extra:
  recipe-maintainers:
    - aerijman
