{% set name = "adpred" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name }}" 
  version: "{{ version }}"

source:
  url: https://github.com/FredHutch/{{ name }}/archive/v{{ version }}.tar.gz  
  sha256: 1af88ca34225f819edf3f17fd7abd0aaaec211435278cd4df3039c31dcebb8f5  

build:
  number: 0
  noarch: python
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt 

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - keras==2.2.4
    - scikit-learn==0.21.3
    - numpy==1.17.2
    - plotly==4.1.1
    - tensorflow==1.14.0
    - requests==2.23.0

test:
  imports:
    - adpred

about:
  home: https://github.com/FredHutch/adpred
  license: MIT Licence
  summary: "python adpred module for prediction of Transcription activation domains from protein sequences"

extra:
  recipe-maintainers:
    - aerijman
